### ISSUE TITLE
How to visualize data from a live server?

### ISSUE THREAD

**Issue by baker-Xie** [cruise-automation/webviz#118]
We want to run our ros application, and transfer the data to worldview to visualize. But how to connect the C++ Ros node to worldview? Thanks

**Comment by janpaul123** [comment]
This is currently not possible. We are working on bringing Worldview into [Webviz](https://cruise-automation.github.io/webviz/webviz-core.html) (see #104), which will allow you to drag in a recorded ROS bag file and visualize it in 3D. But connecting to a live ROS application is a bit more difficult. We might support that in the future.

**Comment by Zanbrachrissik** [comment]
> This is currently not possible. We are working on bringing Worldview into [Webviz](https://cruise-automation.github.io/webviz/webviz-core.html) (see #104), which will allow you to drag in a recorded ROS bag file and visualize it in 3D. But connecting to a live ROS application is a bit more difficult. We might support that in the future.

Hi, I wonder if you connected to webviz for real time visualising. I am currently working on it and I really appreciate it if you could give me some help.

**Comment by jtbandes** [comment]
@Zanbrachrissik there's more discussion on this in #170.

**Comment by janpaul123** [comment]
@baker-Xie @Zanbrachrissik This is now working, see https://github.com/cruise-automation/webviz/pull/299 for details!
