### ISSUE TITLE
How to visualize ros topic in real time

### ISSUE THREAD

**Issue by yukkysaito** [cruise-automation/webviz#129]
Can I view the topic of ros in real time?
(Will this replace Rviz in the future? Rviz is heavy processing load... )

thank you

**Comment by janpaul123** [comment]
We currently only support bag files, but we might support connecting to a live ROS master in the future (see https://github.com/cruise-automation/webviz/issues/118).

**Comment by yukkysaito** [comment]
I am looking forward to it. thank you
