### ISSUE TITLE
how to control the playing process

### ISSUE THREAD

**Issue by yokyj** [cruise-automation/webviz#144]
Hi
I see that the webviz uses rosbag.js to read a ros bag file which is also maintained by cruise.
But I can't find the code that how you control the process like pause.
The way to get the result is to call bag.readMessages(options, callback),how I can pause a callback?Or is there a graph showing the webviz's data flow?

sincerely
Keyj

**Comment by janpaul123** [comment]
Currently there is no diagram, that's a good idea though. If you want a concept of play/pause you can just make lots of calls to `bag.readMessages` that span short time ranges. That's what we do in Webviz. Hope that makes sense?

**Comment by yokyj** [comment]
That helps.Thank you
