### ISSUE TITLE
ERROR:Missing 1 theme converted to base_link : / lidar side front(frame:lidar side front)

### ISSUE THREAD

**Issue by fatboyd** [cruise-automation/webviz#172]
When I drag the package gnss_raw_0 into webviz, the page appears：Missing 1 theme converted to base_link : / lidar side front(frame:lidar side front)，How can I solve this problem?

**Comment by jtbandes** [comment]
Can you share a link to the data you're using?

I recently noticed that during the tf2 migration, new behavior was added that will strip `/` from the beginning of frame ids: http://wiki.ros.org/tf2/Migration  We might need to make some changes in Webviz to do this automatically for data that has a mix of slashes and no slashes.

**Comment by jtbandes** [comment]
This should be fixed now; as of #174, we strip leading slashes from TF frames ids.
