### ISSUE TITLE
Issues with decoding .glb files

### ISSUE THREAD

**Issue by spjy** [cruise-automation/webviz#197]
I am attempting to load .glb files other than the Duck and CesiumMan that are provided in the [GLTFScene example](https://webviz.io/worldview/#/docs/commands/gltfscene). I have tried to import my own models as well as ones provided in the example model repository [here](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0) such as `Box.glb` and `RiggedSimple.glb`, but I always get the error "Error decoding GLB file".

I have forked your GLTFScene example and tried importing my own model to it, namely `rectangle.glb` and I get the same error as above. All the models are located in `/utils/Models`.

Example: https://codesandbox.io/s/agitated-star-ruxr4?fontsize=14

**Comment by jtbandes** [comment]
Thanks for the report. This looks like a regression caused by #198; we'll look into it soon. cc @davidswinegar

**Comment by jtbandes** [comment]
Tested out your CodeSandbox again and it looks like it's working now, after David's fix:

![image](https://user-images.githubusercontent.com/14237/64647684-4f612100-d3ce-11e9-9378-4cd7f094b73e.png)
