### ISSUE TITLE
A problem to watch webviz demo, player is always initializing

### ISSUE THREAD

**Issue by masakisonic** [cruise-automation/webviz#204]
Hi, I have a problem on watching webviz demo from [https://webviz.io/try/?demo](https://webviz.io/try/?demo), 
**The player always waits for initializing**, so I can't watch the demo.

I use Chrome on Windows 7 and its version
> 76.0.3809.100 (Official Build) (64-bit)

I also try my phone & ubuntu 16.04, but the same result for me.

Does anyone know if I lose some plugins or other things on watching demo?
Thanks.

![2019-08-22_webviz_demo](https://user-images.githubusercontent.com/54402303/63513763-a8e5d680-c519-11e9-8e2c-af8601f1b3e0.png)

**Comment by janpaul123** [comment]
Oh you're right, thanks for reporting, we'll look into it!

**Comment by troygibb** [comment]
It should be fixed now!!! Sorry for the inconvenience.
