### ISSUE TITLE
Failed to build and test

### ISSUE THREAD

**Issue by hakuturu583** [cruise-automation/webviz#210]
I want to build webviz.
I install npm and nodejs and type

```
npm run bootstrap
```

It was success, but I typed 

```
npm run test
npm run build
```

All of them are failed.

**Comment by hakuturu583** [comment]
![image](https://user-images.githubusercontent.com/10348912/63681353-94af1b80-c830-11e9-8522-7715f5765d28.png)

**Comment by jtbandes** [comment]
Let us know if you have any more problems!
