### ISSUE TITLE
MouseEvent arguments mix-up

### ISSUE THREAD

**Issue by conrad** [cruise-automation/webviz#226]
Hello, I've just upgraded to v0.2.2, and two of the fields seem to have been swapped unintentionally. Previously, the arguments were `event, { ray, object(s) }`. 

Now, I'm seeing that the second argument is still an object with the field ray, but this field then points to a mouse event object. Meanwhile, the first argument sent turns out to be a ray. To explain a little more this what the second argument looks like now: 
```
{
  objects: [{…}]
  ray: Class
    altKey: false
    bubbles: true
    button: 0
    buttons: 0
    cancelable: true
    clientX: 640
    clientY: 233
    ctrlKey: false
    ...
  }
}
```

That Ray looks a lot like a MouseEvent...

I'm guessing this was just an accident. I'll switch these out in my code, in the meantime, and leave myself a note.

**Comment by conrad** [comment]
Or I'll dig around and make a PR if I find the issue.

**Comment by davidswinegar** [comment]
Thanks for the bug report! I'll take a look at this today.
