### ISSUE TITLE
circle-ci docker image

### ISSUE THREAD

**Issue by stefan-enway** [cruise-automation/webviz#245]
Hi there,i just played around with a fork (and merged all the dependabot PRs on my clone) i noticed you have a docker image to do ci stuff cruise/webviz-ci:0.0.8 is there secret sauce in it or would it be possible to make the Dockerfile for this available?

**Comment by janpaul123** [comment]
That's just this one: https://github.com/cruise-automation/webviz/blob/master/Dockerfile and it's publicly available in dockerhub here: https://hub.docker.com/r/cruise/webviz-ci/tags 😄

**Comment by stefan-enway** [comment]
huh. strange that circle-ci did not pull that, thanks!
