### ISSUE TITLE
Confusion about yarn workspace usage

### ISSUE THREAD

**Issue by wuweiweiwu** [cruise-automation/webviz#321]
Seems like yarn workspaces are used in this monorepo https://github.com/cruise-automation/webviz/blob/master/package.json#L142 but lerna is not utilizing it.

Would it make sense to remove the `workspaces` key from `package.json` since this monorepo uses `lerna boostrap`? or is there plans to migrate -> yarn & workspaces?

**Comment by janpaul123** [comment]
I don't think there are concrete plans to migrate to yarn workspaces, so any cleanup would be welcome! 🙌
