### ISSUE TITLE
Time series plotting support

### ISSUE THREAD

**Issue by acadien** [cruise-automation/webviz#338]
Webviz is useful for quickly plotting of timeseries that are ros compatible. I frequently use it for debugging raw sensor output; for example here is the output from a magnetometer;
![image](https://user-images.githubusercontent.com/375220/73771575-76304300-4733-11ea-8396-5e3f7e13e623.png)

The problem is that points accumulate and eventually the entire browser begins to lag under the weight of rendering all of these points. Any solution that allows me to limit the number of points would be handy, some ideas;
* set the X-axis limit so that as new points come in, old points drop off the back 
* an option to wipe the plot from time to time
* set the maximum number of points rendered and simply drop old ones

**Comment by janpaul123** [comment]
Yeah, this issue was also noted in #312. I think we're gonna go with an x-axis limit (the third option that you mentioned above doesn't work great if topics are publishing at different rates).

**Comment by acadien** [comment]
Excellent thank you @janpaul123

**Comment by acadien** [comment]
duplicate - https://github.com/cruise-automation/webviz/issues/312
