### ISSUE TITLE
/tf not rendered properly in webviz

### ISSUE THREAD

**Issue by acadien** [cruise-automation/webviz#339]
I have a /tf that renders fine in RViz:
![image](https://user-images.githubusercontent.com/375220/73772435-facf9100-4734-11ea-88e3-044d3be99340.png)
but seems to have some issues in webviz,
![image](https://user-images.githubusercontent.com/375220/73772748-9f51d300-4735-11ea-85d3-42f2db3a854b.png)
Is it possible that webviz doesn't consume static portions of the tf tree? Any other thoughts?

**Comment by janpaul123** [comment]
Yes! There's already a PR to fix this at #336. I'll have to look at getting that in soon.

**Comment by acadien** [comment]
duplicate of https://github.com/cruise-automation/webviz/pull/336
