### ISSUE TITLE
Exception calling subscribe callback: 'float' object has no attribute '__slots__'

### ISSUE THREAD

**Issue by ubicray** [cruise-automation/webviz#346]
Why do I get this on the ROS side bridge when I try to plot?
What does that mean? Any idea?

**Comment by jtbandes** [comment]
Can you provide some more details? Which version of ROS, what are you advertising on the topic, publisher side code, etc.

**Comment by ubicray** [comment]
Ros Kinetic
Happens with a lot of kinds of topics but not all
For example if I try to plot latitude values from sensor_msgs/NavSatFix Message

**Comment by janpaul123** [comment]
Ah I think this should get fixed once we implement the webviz side of this PR: https://github.com/RobotWebTools/rosbridge_suite/pull/452 We'll have to make some time for that soon, so stay tuned!

**Comment by Sollimann** [comment]
I have the same issue when subscribing to /odometry /tf /joint_states messages. How's the fix doing? Btw, great tool you have here!

**Comment by meitiever** [comment]
I have the same issue even if I subscribe to image topic.

**Comment by janpaul123** [comment]
This should be fixed now since #396. You'll have to use the latest version of the rosbridge now. Let me know if you still have any issues!
