### ISSUE TITLE
Is this official Docker img ? johannhaselberger/webviz

### ISSUE THREAD

**Issue by chengtz** [cruise-automation/webviz#351]
Tried to install many times , alyways error
so i go searching the docker img , i found this johannhaselberger/webviz
the img packed six mon ago , not the latest version.
Any official docker img will be published ?

**Comment by janpaul123** [comment]
No, currently we recommend you use the version at webviz.io/app instead of building your own version. See the discussion at https://github.com/cruise-automation/webviz/issues/304
