### ISSUE TITLE
[feature request] Expose the current epoch

### ISSUE THREAD

**Issue by jasonimercer** [cruise-automation/webviz#379]
Webviz is a great collaborative triage tool. Often we would like to be able to create links that would seek to a specific timestamp in a stream but there's no easy way to pull the current timestamp out of the UI. Copying the epoch in the format expected by the `seek-to` to the clipboard would be enough, generating a full link with new or updated seek-to (like youtube) would work too.

Even exposing a javascript function like `this_is_not_a_stable_API_getEpoch()` would allow tooling built around Webviz to do the formatting with the understanding that everything is in flux and we run at risk if we depend on compatibility from commit to commit.

**Comment by janpaul123** [comment]
I forgot to put this in the changelog, but this is in the latest release. #396 It should get deployed to our production application in a bit. Thanks for the request!
