### ISSUE TITLE
How to add custom ros message to visualize 

### ISSUE THREAD

**Issue by tlgkyn06** [cruise-automation/webviz#409]
Hi , I'm trying to visualize 3D world mapping with data that comes from my custom ros messages. I tried to trace the code; it seems I need to modify https://github.com/cruise-automation/webviz/blob/master/packages/webviz-core/src/types/Messages.js and https://github.com/cruise-automation/webviz/tree/master/packages/webviz-core/src/panels/ThreeDimensionalViz . Is there any guide for how to add ros messages or any body to help?
Regards.

**Comment by janpaul123** [comment]
I would recommend having a ROS node that converts your messages into one of the standard ROS message formats, which are the same as the message formats supported by rviz: https://github.com/cruise-automation/webviz/blob/6623f080b2bee11144df1bb70c2ac93db51a37fa/packages/webviz-core/src/panels/ThreeDimensionalViz/SceneBuilder/index.js#L450
