### ISSUE TITLE
Loader splash image persists after remote bags load / webviz initializes (Related to Chrome Extensions)

### ISSUE THREAD

**Issue by jasonimercer** [cruise-automation/webviz#412]
Some of our test team are having issues with the splash animation persisting

Running master from this morning.
Ubuntu 16.04
Chrome: Version 81.0.4044.113 (Official Build) (64-bit)

![image (1)](https://user-images.githubusercontent.com/12039018/80628693-bf84eb80-8a1f-11ea-9817-8fbe4798dde7.png)
![image (2)](https://user-images.githubusercontent.com/12039018/80628698-c1e74580-8a1f-11ea-944b-a0723b11fb22.png)

**Comment by janpaul123** [comment]
Oof oh no! Any errors either in the browser console or in the top bar?

**Comment by jasonimercer** [comment]
The console is showing


webpack-internal:///./node_modules/react-dom/cjs/react-dom.development.js:558 Warning: Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.

**Comment by jasonimercer** [comment]
Seems 2 chrome extensions were running: LastPass and Toby. With both disabled the issue went away, I'll work on getting the steps to reproduce on a fresh machine, forward the info along and you can decide if it's something that should be fixed, documented or ignored for now.

**Comment by janpaul123** [comment]
Ooh funky, yeah browser extensions can do strange things. Also be sure to check out #407 — we'll merge that soon once we've fixed the screenshot tests, but it contains a bunch of bugfixes and such.

**Comment by jasonimercer** [comment]
OK, I couldn't reproduce the issue reported. We'll add the reminder about extensions to our internal pages for WebViz.

Since I can't reproduce and we have a workaround for the people who reported this, I'm happy to have this closed and chalk it up to "spooky extension stuff".

**Comment by jasonimercer** [comment]
407 Looks great! Can't wait to update :)

**Comment by janpaul123** [comment]
Sounds good; I'll close this out then!
