### ISSUE TITLE
webviz won't connect to robot?

### ISSUE THREAD

**Issue by bumblebeerobotics** [cruise-automation/webviz#423]
Hello I'm, trying to use WebViz for a project and I'm not sure what is going on/why it is not working. 

I have a remote websocket running for my ROS robot at ws://192.168.1.24:9090 and I changed the ports and URL and everything so I ran https://webviz.io/app/?rosbridge-websocket-url=ws://192.168.1.24:9090/ in the web browser. 

And I went to google chrome settings and changed the settings to allow insecure connections. What am I doing wrong here? Why can't I get webviz to connect to a remote websocket?

**Comment by jtbandes** [comment]
What errors are you seeing?

**Comment by bumblebeerobotics** [comment]
I'm not seeing any errors which is why I'm confused. When I tried to connect to this web-socket using ROSWEB it connected fine and I was able to get data out of the system. And then if I look on my robot itself the rosbridge outputs to /rosout "one client connected." or something similar

I went to webviz and put in the same ws url, and /rosout showed no message that there was a client connected?

**Comment by bumblebeerobotics** [comment]
For reference: this works: https://github.com/EESC-LabRoM/rosweb

**Comment by bumblebeerobotics** [comment]
For a little more information: I brought up a Raw Messages panel on the webviz and typed /joy to see the raw messages for /joy that's what I started with trying (my bigger issue is that I don't see the client connected though as I described above)

**Comment by janpaul123** [comment]
What version of `rosbridge_server` are you running?

**Comment by bumblebeerobotics** [comment]
I just went here: http://wiki.ros.org/rosbridge_suite/Tutorials/RunningRosbridge and did sudo apt install ros-melodic-rosbridge-suite ... does that give me the latest version? How would I check?

**Comment by janpaul123** [comment]
You can check by running `apt policy ros-melodic-rosbridge-server`. Which version gets installed when you run `apt install` depends on a bunch of things.

**Comment by bumblebeerobotics** [comment]
<img width="588" alt="Screen Shot 2020-05-11 at 7 00 32 PM" src="https://user-images.githubusercontent.com/46380543/81620397-bef23a80-93b9-11ea-895c-638899f339f6.png">

Here is the version (I think it's 0.11.5-1bionic.20200413.152945). Thanks for the info :)

**Comment by janpaul123** [comment]
Hm, that version should be fine. 0.11.6 is the latest, but 0.11.5 should work. Could you maybe record a video of what's happening? If we can't figure it out from that, I might be able to set you up with a screenshare with someone on our team.

**Comment by bumblebeerobotics** [comment]
Hey! Here's a link to the video I recorded, I'm ssh'ed into the robot from VS Code and then the google Chrome is on my macbook. 

https://www.adim.io/post/chip-updates-websocket-won-t-work-updates

**Comment by bumblebeerobotics** [comment]
let me know if you need more information?

**Comment by janpaul123** [comment]
Hm not sure, can you email me at jp.posma@getcruise.com and we can do a screen share.

**Comment by flynneva** [comment]
try passing the devices IP address to the rosbridge_webserver. it looks like right now you're just [passing in the default which is `localhost`](https://answers.ros.org/question/250959/connecting-different-computers-via-rosbridge/).

also, look into these other topics which seem similiar:
- [wss support](https://github.com/RobotWebTools/rosbridge_suite/issues/232)
- [wss support 2](https://github.com/RobotWebTools/rosbridge_suite/pull/27)
- [wss support 3](https://answers.ros.org/question/207068/rosbridge-cannot-connect-to-secure-websocket-timed-out-error/)

**Comment by bumblebeerobotics** [comment]
I'll definitely try adding the IP to rosbridge_webserver, but I also enabled "use unsafe scripts" for webviz on chrome will that not fix the security issue with https?

**Comment by bumblebeerobotics** [comment]
Are you saying I need to do : https://answers.ros.org/question/198647/rosbridge-websocket-ssl-connection-aborted/ kind of stuff to setup ssl?

**Comment by flynneva** [comment]
my comment above was just providing some comments on where I think the issue is. since all we have is just a video to debug from and its not entirely clear what the issue is, I cant really say what will solve your problem.

**Comment by bumblebeerobotics** [comment]
thanks for the info :) I was just wondering if saying my robot was running a jetson tx1 does that change anything? realized I haven't mentioned that and that I know they're kinda weird.

**Comment by flynneva** [comment]
a good way to test if this is the issue is to try webviz from the device directly from the device.
can you connect the jetson tx1 to a monitor and open a browser with webviz there?

**Comment by flynneva** [comment]
I know this kind of defeats the purpose of what you are trying to do...but a good debug step would be to test webviz locally on the jetson tx1 (if you can hook it up to a monitor & get a browser open). if that works, then it most likely is an issue with the security (https vs http) as linked above.

**Comment by bumblebeerobotics** [comment]
Ah. This was a good suggestion! I did hook it up and run a local test and it does work locally so I think you're right on the ssl permissions side. I'm speaking with JP in a few minutes and I think we'll come up with a solve - if not I'll re-post here if we do, I'll close the issue :) Thanks so much for your help.

**Comment by bumblebeerobotics** [comment]
JP called me and we fixed the problem - thank you so much t of both of you - it was lovely meeting you guys!

**Comment by janpaul123** [comment]
For future reference, we had to do this:

![](https://raw.githubusercontent.com/cruise-automation/webviz/ccd6acc801d333310c2c13e1ae113867f17df699/packages/webviz-core/src/components/WssErrorModal.png)

A modal with this image + some instructions should have been shown though, so that's a bug that I'll have to look into. Nice meeting you too Adi!

**Comment by jaguardo** [comment]
I'm not seeing that option on any of the browsers I've tried... is there a browser setting to change?

**Comment by jaguardo** [comment]
So for those that are interested, for Chrome I had to do a few extra steps... I wasn't getting the "sheild" and at first I was getting the "Secure" symbol on Chrome:  
![image](https://user-images.githubusercontent.com/28798269/101776715-60ac4800-3abf-11eb-8ed6-f6d6d6725947.png)
even when I added the ip address to another computer on the network. makes it appear everything is ok... unfortunately it will not load!! with no warning on why...  
![image](https://user-images.githubusercontent.com/28798269/101776776-791c6280-3abf-11eb-825b-d7853714a327.png)
so, by clicking on the "lock"
![image](https://user-images.githubusercontent.com/28798269/101776852-98b38b00-3abf-11eb-8275-e15ebe93179c.png)
and opening site settings:
![image](https://user-images.githubusercontent.com/28798269/101776916-a9fc9780-3abf-11eb-85d3-281160351dfd.png)
I can set chrome for that website to allow insecure content:
![image](https://user-images.githubusercontent.com/28798269/101776970-c698cf80-3abf-11eb-96ec-973aac8f40a4.png)
you can now reload the page (Chrome will pimp you to do this anyways)
now, when you load the basic website:
```
https://webviz.io/app/
```
you will still see the traditional lock, but when you use the alternative address for an ip, you will not get the lock, but a nice "not secure" warning and the shield as you would in previous editions of chrome?
![image](https://user-images.githubusercontent.com/28798269/101777299-47f06200-3ac0-11eb-843b-6179ff616e21.png)
now by clicking on the shield you can load those scripts:
![image](https://user-images.githubusercontent.com/28798269/101777351-5b033200-3ac0-11eb-90f6-c29c30793f19.png)
hope it helps someone!

**Comment by vidaaudrey** [comment]
Thank you @jaguardo  for documenting the details.

**Comment by marcelino-pensa** [comment]
Would it be possible to add a link to this issue in the error message that `webviz.io/app` shows up? I spent quite a bit of time trying to figure out why my `shield` wasn't showing up, which could be easily solved by visiting this page (I had to google very specifically to end up in here)

**Comment by cjds** [comment]
@vidaaudrey do you mind if I make a PR that updates the help?

**Comment by vidaaudrey** [comment]
@cjds  thank you! Please feel free to make a PR for this and tag me for reviewing :)
