### ISSUE TITLE
Slack invite link

### ISSUE THREAD

**Issue by janpaul123** [cruise-automation/webviz#461]
Since Slack invite links expire after 30 days, I figured we can just post them here whenever it's needed.

**Comment by janpaul123** [comment]
https://join.slack.com/t/webvizchat/shared_invite/zt-evd6yzee-MmfUfe_hRvf~t9HBPpKkdQ

**Comment by maxlein** [comment]
Pls update the invite

**Comment by troygibb** [comment]
Here you go! https://join.slack.com/t/webvizchat/shared_invite/zt-h036wkmu-y5AxRCzSRdNbAJw0zYMA4g

**Comment by lukicdarkoo** [comment]
Please update the link

**Comment by troygibb** [comment]
Done! https://join.slack.com/t/webvizchat/shared_invite/zt-hyo9jggj-n4dwegVa290HM5PpPRWBZw

**Comment by rgov** [comment]
@troygibb A new link please?

**Comment by troygibb** [comment]
Done again! https://join.slack.com/t/webvizchat/shared_invite/zt-j6z2kcbl-aJHPkK~99~oYHv7LWrODRA

**Comment by CalvinKroese** [comment]
@troygibb Could you send a new link please?

**Comment by troygibb** [comment]
Done again again! https://join.slack.com/t/webvizchat/shared_invite/zt-k3nj8jx0-qhg~wTmqfklJWVjPRWiVBQ

**Comment by ammaryasirnaich** [comment]
Please can you send the invitation link !

**Comment by inactivist** [comment]
Please provide a new invitation link.  The most recent one has expired.

![image](https://user-images.githubusercontent.com/1195074/105197411-7286ff00-5af1-11eb-9961-4b0797b8c92d.png)

**Comment by troygibb** [comment]
here you go! https://join.slack.com/t/webvizchat/shared_invite/zt-l7x2ocqc-2uuhztdaOv50GtzTQh8jLg

**Comment by yashvakil** [comment]
The link has expired could you share another

**Comment by troygibb** [comment]
Done. https://join.slack.com/t/webvizchat/shared_invite/zt-mrp65eb6-ZOrtb1qXrofFRXqYBvpyXw

**Comment by shreyas2311** [comment]
The link has expired. Can you share another? thanks

**Comment by troygibb** [comment]
https://join.slack.com/t/webvizchat/shared_invite/zt-ou31t3sg-wyaa0fpTby1KvJXGbXPuvg

**Comment by m2themax** [comment]
Link has expired. Can you please post a new one. Thanks!

**Comment by troygibb** [comment]
https://join.slack.com/t/webvizchat/shared_invite/zt-q58hdnw0-HeV8QkOumMQDrBgtzm5jYg

**Comment by thewalk** [comment]
please share a new link, thanks!

**Comment by troygibb** [comment]
https://join.slack.com/t/webvizchat/shared_invite/zt-r6f2atsn-5yYHSG7JaPqtbMJUbatpaA

**Comment by nonlinear1** [comment]
This link is no longer active. Could you send a new link?

**Comment by troygibb** [comment]
https://join.slack.com/t/webvizchat/shared_invite/zt-t0xhhiur-VZZrViVqbYLOwWpYJB9PZw

**Comment by stefan-pdx** [comment]
Hi @troygibb. Would you mind updating the link please? Thanks!

**Comment by ShepelIlya** [comment]
@troygibb Could you post a new link please?

**Comment by troygibb** [comment]
https://join.slack.com/t/webvizchat/shared_invite/zt-um7wbhu9-xaMavlo6AVwoWZsTaa7Upg

**Comment by rfsch** [comment]
@troygibb Could you post a new link please? Thanks!

**Comment by Wudadad** [comment]
> @troygibb Could you post a new link please? Thanks!

+1

**Comment by troygibb** [comment]
sorry for the late reply! https://join.slack.com/t/webvizchat/shared_invite/zt-wfu6cctt-k5L2dN6XoZWbX_ULm8QFGQ

**Comment by jtbandes** [comment]
FYI, we also have a Slack for [Foxglove Studio](https://github.com/foxglove/studio) (Webviz fork) here: https://foxglove.dev/slack

**Comment by AnExplorer28** [comment]
Hi, the Previous link is no longer active. Can you please share the new link? Thanks!

**Comment by troygibb** [comment]
https://join.slack.com/t/webvizchat/shared_invite/zt-yjc7katc-iqH1Lc0b1Tmm6LxiuPFvkQ

**Comment by Beaudidly** [comment]
Hey! Could I please have an updated invite please?

**Comment by troygibb** [comment]
https://join.slack.com/t/webvizchat/shared_invite/zt-112b2nhdg-wmyG19eD03hfymkMKIsFsA

**Comment by vicente879** [comment]
Hi, the current link has expired. Could you post an updated invite please? thanks!

**Comment by C1oudust** [comment]
Hey! Could I please have an updated invite please?

**Comment by teknetik** [comment]
Please could we have an updated invite?

**Comment by rsinnet** [comment]
Updated invite please?

**Comment by LJL0511** [comment]
> Could you send a new link please?

**Comment by amacneil** [comment]
Most of the former Webviz chat has moved to the Foxglove Slack channel, you can join here: https://foxglove.dev/slack
