### ISSUE TITLE
Can't visualize lidar data on Webviz 

### ISSUE THREAD

**Issue by rawanbadr** [cruise-automation/webviz#469]
I am running webviz locally and i am playing the rosbag in the background in order to visualize it.The image data is working perfectly after selecting the topic but the lidar data is giving the following error in the picture ,any help please?
![WhatsApp Image 2020-06-23 at 12 37 48 AM](https://user-images.githubusercontent.com/47105825/85343102-520bad80-b4ec-11ea-8550-29d793f82231.jpeg)

**Comment by janpaul123** [comment]
You might have to select a different root TF in the top right.
<img width="146" alt="Screen Shot 2020-06-22 at 4 02 44 PM" src="https://user-images.githubusercontent.com/177461/85343491-d2f18780-b4a1-11ea-81ef-ac56ba1bb914.png">

Also feel free to join us on Slack: #461.

**Comment by rawanbadr** [comment]
i still do have the same issue

**Comment by vidaaudrey** [comment]
@rawanbadr Could you record a sample bag and share with us?

**Comment by janpaul123** [comment]
@vidaaudrey we're chatting with them on Slack!

**Comment by castaway2000** [comment]
I am also having the same issue but with an Ouster Lidar Sensor.

**Comment by vidaaudrey** [comment]
@rawanbadr  closing the issue now. Let me know if you still have problem visualizing the topic.
