### ISSUE TITLE
Marker Array Points Not Scaled Correctly

### ISSUE THREAD

**Issue by jasonimercer** [cruise-automation/webviz#491]
Points in a Marker Array message are scaled in units of pixels rather than meters as the unit in other elements.

issue:

https://github.com/cruise-automation/webviz/blob/master/packages/regl-worldview/src/commands/Points.js#L32

vs

code that considers the camera:

https://github.com/cruise-automation/webviz/blob/master/packages/regl-worldview/src/commands/Lines.js#L147-L151

rviz and webviz visualizing points in a marker array:
![image (23)](https://user-images.githubusercontent.com/12039018/89295041-633cf380-d62e-11ea-91d0-8312688ddb38.png)

example input with points in a marker array 
[2020-07-28-12-26-37.bag.gz](https://github.com/cruise-automation/webviz/files/5022124/2020-07-28-12-26-37.bag.gz)

**Comment by troygibb** [comment]
Thanks @jasonimercer for reporting! We may have to refactor our `<Points />` command to account for this issue. 

Can you describe your use case a bit more? Why do you need to express points so exactly? Why not use some of our other primitive shapes?

cc @hhsaez

**Comment by jasonimercer** [comment]
We use Marker Arrays for rich diagnostics. Our code publishes lines, polygons, arrows, text, points to give our triage teams an easier view into the state of the robot and the surroundings.

In this marker array we denote remembered obstacles that were point-like as well as obstacles that were identified as moving polygons. We also show demarcations between regions we can observe and will add data to memory, regions we only use to invalidate memory and regions where we rely on memory.

When we are displaying point-like lidar data in our aggregated memory, the points are single pixels using Webviz (which on modern displays and a busy interface, is as good as invisible - see pixel data in screenshot above). We don't need them to be 100% accurate, we just need them to be visible similar to RViz so we can continue to shift the hold-outs towards webviz.

**Comment by jasonimercer** [comment]
Callout added to image above demonstrating issue:

![89295041-633cf380-d62e-11ea-91d0-8312688ddb38](https://user-images.githubusercontent.com/12039018/89418377-f85aed80-d6fd-11ea-9bb0-434a4c9091b3.png)

**Comment by troygibb** [comment]
Thanks Jason for the context -- I just wrote a ticket to track this issue internally.

**Comment by jasonimercer** [comment]
I see code has been merged related to this case. Is it live on the demo site or is there something that needs to be done to trigger it? When I load my example bag file above into the demo site the display appears the same.

**Comment by troygibb** [comment]
We're still waiting on some internal updates to be made before updating open source with the new change. @hhsaez can you make sure to update open source once that PR lands?

**Comment by jasonimercer** [comment]
Wonderful, happy I wasn't missing something obvious on the demo site :)

**Comment by hhsaez** [comment]
@jasonimercer! Webviz has just been updated with the fix for point sizes. Please give it a try when you have the chance.

**Comment by jasonimercer** [comment]
Brilliant! I'll try today.

**Comment by jasonimercer** [comment]
There may be a factor of 2 issue somewhere? Throwing the test bag above into the live server shows a difference but feels like the squares are about 2x too large?

I'll look closer this evening.

**Comment by jasonimercer** [comment]
![image](https://user-images.githubusercontent.com/12039018/96592411-5b4c3180-12b6-11eb-999d-d27920d78af8.png)

Looks like the marker array boxes are now 1m across while the scale calls for a 0.2m x 0.2m boxes.

**Comment by iwanders** [comment]
I've filed #529 , which fixes the point scaling with scales below `1.0`.

**Comment by iwanders** [comment]
@jasonimercer, I think this issue can be closed now that the scaling is correct in the latest version of `master`?
