### ISSUE TITLE
Failed to decode image on ios chrome

### ISSUE THREAD

**Issue by XinnWang** [cruise-automation/webviz#502]
Hi, thanks for the great work!

i want to open the Webviz on my iphone or ipad. i am using the chrome but got following warning when opening the url:

<img width="200" alt="chrome_update" src="https://user-images.githubusercontent.com/5515327/91866702-61099b80-eca5-11ea-9626-1a960b1c7149.png">

after choosing the "continue anyway", i got following error:

<img width="500" alt="image_decode_failed" src="https://user-images.githubusercontent.com/5515327/91867183-ed1bc300-eca5-11ea-9ca8-5f61b4b6d0b1.png">

it said "webviz failed to decode image". What should i do ? Thanks.

**Comment by troygibb** [comment]
Thanks @XinnWang! We don't officially support iOS or iPadOS-- so there may be an issue. It would be also helpful to know whether this works on your desktop browser.

**Comment by XinnWang** [comment]
@troygibb  is Android supported?

**Comment by troygibb** [comment]
Not officially.
