### ISSUE TITLE
change color of radar points in 3D panel

### ISSUE THREAD

**Issue by sky4133** [cruise-automation/webviz#522]
In my Webviz, the color of online radar points is only white with black background,
how could I change the color to "Rainbow" like the Demo from Webviz.

Ps, when the key "colorMode", which is copied from Webviz demo, was add into Json of panel setting , nothing changed.
  "settingsByKey": {
    "t:/rslidar_points": {
      "colorMode": {
        "mode": "rainbow",
        "colorField": "ring"
      }
    }
}

**Comment by vidaaudrey** [comment]
@sky4133  if you color by `ring`, you'll need to make sure this field is actually available in the lidar data. Otherwise, you can always choose to color by other available fields. 
![color](https://user-images.githubusercontent.com/10999093/94639515-2dfcfc80-0291-11eb-8f6f-fd3518ccd70f.gif)

**Comment by sky4133** [comment]
thank you !!! it works
