### ISSUE TITLE
Error playback demo.bag in clean chrome

### ISSUE THREAD

**Issue by Uezzi** [cruise-automation/webviz#538]
First congratulation for the great Webviz project! However, I have an issue testing the demo.bag file (downloaded [here](https://open-source-webviz-ui.s3.amazonaws.com/demo.bag)). I'm using google chrome 86.0.4240.111 after clearing the complete history including caches.

If I browse the Webviz page (e.g. the [hosed one](https://webviz.io/app)) and drop the demo.bag file there and activate the topic /velodyne_points, the following error occurs: missing transforms to root transform map.
If I browse the demo, using the ?demo prefix, everything looks fine. After browsing the ?demo I'm going back to the [app page](https://webviz.io/app). If I drop the demo.bag file again, everything looks fine, too. The same issue can be seen if using Inkognito mode in chrome.

**Comment by vidaaudrey** [comment]
Hi @Uezzi, if you change the follow option to `velodyne` at the right side of the 3D panel, you should see the the markers showing up. Let me know if you still have issues. 

![image](https://user-images.githubusercontent.com/10999093/97597339-f33ad100-19c2-11eb-8958-1346eb2591ab.png)

**Comment by Uezzi** [comment]
Hi @vidaaudrey , it works now. Thanks for your help!
