### ISSUE TITLE
How to set the background of text label information to be fully transparent？

### ISSUE THREAD

**Issue by sky4133** [cruise-automation/webviz#578]
At present, the background of Label information (such as speed, target type, etc.) is black, as shown in the figure, how to set it to transparent.
![label_background](https://user-images.githubusercontent.com/34745111/104157606-6da5b980-5426-11eb-9306-784cfc80a469.jpg)

**Comment by sky4133** [comment]
At present, the background of Label information (such as speed, target type, etc.) is black, as shown in the figure, how to set it to transparent.
![label_background](https://user-images.githubusercontent.com/34745111/104157303-d93b5700-5425-11eb-85fe-2ebc5375ed98.jpg)

**Comment by vidaaudrey** [comment]
@sky4133 you could turn it the `Auto text backgroudcolor` off from the settings menu:
![image](https://user-images.githubusercontent.com/10999093/104216006-5f3bab80-53ee-11eb-8f35-cca420745825.png)

**Comment by sky4133** [comment]
It works ! Thank you @vidaaudrey !
