### ISSUE TITLE
2d view is not actually flat

### ISSUE THREAD

**Issue by janpaul123** [cruise-automation/webviz#597]
It's an orthographic projection I think, which might not be always obvious. Maybe useful to at least mention in a tooltip or so? Or would it be better to use a projection that completely flattens the z-axis?

Example using the demo bag (https://webviz.io/app/?demo)

![webviz-2d](https://user-images.githubusercontent.com/177461/110873340-9f47cf00-8275-11eb-8aa8-bf4a43b3cddd.gif)

**Comment by jtbandes** [comment]
I'm not sure what your recording is showing — it looks like you have 3D mode enabled?

**Comment by janpaul123** [comment]
LOL my bad 🤦🏻 2d mode does exactly what we want it to hurray!

**Comment by jxjshaw** [comment]
classic

**Comment by janpaul123** [comment]
Lol rub it in Jeff 😂 Glad you're still lurking!
