### ISSUE TITLE
slack invite link

### ISSUE THREAD

**Issue by rfsch** [cruise-automation/webviz#671]
Hi 
can you please share a new slack invite link ? 

Thanks

**Comment by amacneil** [comment]
Webviz Slack link [here](https://join.slack.com/t/webvizchat/shared_invite/zt-wfu6cctt-k5L2dN6XoZWbX_ULm8QFGQ).

We also have a Slack for [Foxglove Studio](https://foxglove.dev) (Webviz fork) [https://foxglove.dev/slack](here).

**Comment by amacneil** [comment]
See also https://github.com/cruise-automation/webviz/issues/461
