### ISSUE TITLE
Integrating Webviz into an existing React application

### ISSUE THREAD

**Issue by eden-desta** [cruise-automation/webviz#679]
Hi!
1) I want to say this library is beautiful -- I am in awe 
2) I have a standalone React application that needs some sort of visualisation aspect for the ROSbags we have (live and pre-recorded). I was wondering if there is a way for me to pull Webviz (core) into an existing application?

It might be pretty straight forward and this might be a useless question, but I have no clue where to get started on doing that, or if there is some docs to do that currently.

Thank you!!! Appreciate your time.

**Comment by denesh-globotix** [comment]
Sure, this is how it looks on the webpage we are working on: 
![image](https://user-images.githubusercontent.com/87276217/139556245-c4db95d5-36e6-4455-b316-7f5df9161104.png)

and this is the link to see it in action: https://jsfiddle.net/den_globotix/vrsyw490/

**Comment by eden-desta** [comment]
Amazing thank you for sharing!
