### ISSUE TITLE
API to stream data to webviz instead of file/rosbag?

### ISSUE THREAD

**Issue by aniongithub** [cruise-automation/webviz#740]
Is there any API or provision to stream data directly to a running instance of webviz instead of relying on a rosbag file?

**Comment by jtbandes** [comment]
If you're using ROS, you can try the [Rosbridge connection](https://github.com/cruise-automation/webviz/blob/d82468c05fb2d3aeca670ff37999faeafa4d7ffc/packages/webviz-core/src/util/helpModalOpenSource.help.md#websocket) via `?rosbridge-websocket-url=ws://...`.

There's more documentation for this feature in [Foxglove Studio](https://github.com/foxglove/studio) here: https://foxglove.dev/docs/studio/connection/live-connection#rosbridge. And we also have a [custom WebSocket protocol](https://foxglove.dev/docs/studio/connection/live-connection#foxglove-websocket) for non-ROS users.

**Comment by aniongithub** [comment]
Thanks, I'll try both those approaches!
